import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DavidRoa',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='global_container'>
        <aside className={inter.className}>
          <Navbar />
        </aside>
        {children}
      </body>
    </html>
  )
}
